"""add totp columns to user

Revision ID: 6ef69797154f
Revises: f7c3d4e5b6a8
Create Date: 2026-05-14 20:21:25.973378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef69797154f'
down_revision = 'f7c3d4e5b6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enrolled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recovery_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recovery_codes')
        batch_op.drop_column('totp_enrolled_at')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
